apiVersion: apps/v1
kind: Deployment
metadata:
  name: soliuproject
  labels:
    app: soliuproject
spec:
  replicas: 1
  selector:
    matchLabels:
      app: soliuproject
  template:
    metadata:
      labels:
        app: soliuproject
    spec:
      containers:
        - name: soliuproject
          image: 499156924743.dkr.ecr.us-east-2.amazonaws.com/soliuproject:1.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
